---
- name: Reload systemctl daemon
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

- name: "update supervisord"
  shell: "supervisorctl update"
  become: yes

- name: "restart zookeeper"
  shell: "supervisorctl restart zookeeper"
  become: yes
